import {get,set,snapshot,put} from './store.js';
import {rows,heads} from './model.js';
import {retrieve,excerpt} from './retrieval.js';
let endpoint='',access='',running=false,timer;
export let aiStatus='AI 尚未连接';
function status(v){aiStatus=v;window.dispatchEvent(new Event('notebook-ai'));}
export const available=()=>!!(endpoint&&access);
export async function hash(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export function withSources(d){const papers=new Map(rows(d,'paper').map(p=>[p.id,p]));return rows(d,'note').map(n=>({...n,source:n.source??(n.paperId==='__inbox'?'':[papers.get(n.paperId)?.title,papers.get(n.paperId)?.source].filter(Boolean).join(' · '))}));}
export const fingerprint=n=>hash(JSON.stringify([n.text,n.source||'',n.locator,n.images]));
async function api(path,body){if(!available())throw Error('请先连接 AI 服务');const response=await fetch(endpoint+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+access,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(65000),redirect:'error'});let data;try{data=await response.json();}catch{throw Error('AI 服务响应异常');}if(!response.ok)throw Error(data.error||'AI 请求未完成');return data;}
export async function connectAI(url,password){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error('AI 服务必须是 HTTPS 地址');endpoint=u.origin;access=password;try{const usage=await api('/usage');await set('ai-endpoint',endpoint);status('AI 已连接');queueClassification();return usage;}catch(e){access='';throw e;}}
export function lockAI(){access='';clearTimeout(timer);status('AI 已锁定');}
export const usage=()=>api('/usage');
export function queueClassification(){clearTimeout(timer);if(available())timer=setTimeout(()=>void classifyPending(),1000);}
async function classifyPending(){if(running||!available())return;running=true;let failed=false;try{await navigator.locks.request('notebook-ai-classify',async()=>{const d=await snapshot();let completed=0;for(const n of withSources(d).filter(n=>!n.archived)){if(!available())break;const fp=await fingerprint(n);if(n.ai?.fingerprint===fp)continue;status('正在整理笔记与截图…');const images=[];for(const id of n.images){const image=await get(id,'assets');if(!image)throw Error('有截图尚未同步，完成同步后会继续整理');images.push(image);}const current=await snapshot(),existingTags=[...new Set(withSources(current).flatMap(x=>x.ai?.tags||[]))].slice(0,100).sort();const result=(await api('/ai',{mode:'classify',text:n.text,source:n.source||'',locator:n.locator,images,existingTags})).result;const latest=await snapshot(),value=withSources(latest).find(x=>x.id===n.id);if(!value||value.archived||await fingerprint(value)!==fp)continue;await put('note',{...value,ai:{...result,fingerprint:fp,at:Date.now()},kind:result.confidence>=.65?result.kind:value.kind},false,heads(latest,'note',n.id).map(x=>x.id).sort().join());window.dispatchEvent(new Event('notebook-ai-result'));if(++completed>=5)break;}status('AI 已连接 · 自动整理就绪');});}catch(e){failed=true;status(e.message);}finally{running=false;if(!failed&&available())timer=setTimeout(()=>void classifyPending(),30000);}}
export async function ask(question){const d=await snapshot(),notes=withSources(d).filter(n=>!n.archived);if(!notes.length)return {matches:[],message:'还没有已保存的笔记。'};if(!available()){const results=retrieve(notes,question);return {local:true,matches:results.map(n=>({id:n.id,quote:excerpt(n.text||n.ai?.ocr||'',question,[],300),reason:'本机关键词匹配，尚未调用 AI',fromOcr:!n.text})),message:'AI 尚未连接，先显示关键词搜索结果。'};}
 status('正在理解问题…');try{const terms=(await api('/ai',{mode:'expand',question})).result.terms,candidates=retrieve(notes,question,terms);if(!candidates.length)return {matches:[],message:'当前可检索的文字中没有找到匹配。可换个说法，或等截图识别完成后重试。'};status('正在核对笔记来源…');const payload=candidates.map(n=>({id:n.id,text:excerpt(n.text,question,terms),source:n.source||'',locator:n.locator,ocr:excerpt(n.ai?.ocr||'',question,terms)})),result=(await api('/ai',{mode:'answer',question,candidates:payload})).result;return {...result,message:result.matches.length?'依据你保存的笔记找到以下记录。':'候选笔记不足以回答这个问题，没有找到有依据的匹配。'};}finally{status(available()?'AI 已连接':'AI 已锁定');}}
window.addEventListener('notebook-local',queueClassification);window.addEventListener('notebook-remote',queueClassification);
