import {rows,conflicts,heads} from './model.js';
import {get,set,snapshot,put,storeImage,exportBackup,importBackup} from './store.js';
import {syncMessage,connect,remember,unlock,synchronize,lock} from './sync.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={note:'随读笔记',quote:'原文摘录',inspiration:'我的启发',question:'问题与思路'},statuses={reading:'正在读',unread:'待读',done:'已读'};
let journal,selected,filter='active',noteFilter='all',editingPaper=null,draft={text:'',kind:'note',locator:'',images:[]},draftQueue=Promise.resolve(),uploading=false,dirty=false,vault=false,saving=false,paperBaseHeads;
const welcome=$('#main').innerHTML;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.display='block';el.style.background=error?'#873f34':'#294d40';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',6000);}
async function run(fn){try{return await fn();}catch(e){toast(e.message||'操作未完成，请重试',true);return null;}}
function saveState(text,error=false){$('#save-state').textContent=text;$('#save-state').classList.toggle('error',error);}
function activePaper(){return rows(journal,'paper').find(p=>p.id===selected);}
function captureDraft(){if(!$('#note-text'))return;draft.text=$('#note-text').value;draft.kind=$('#note-kind').value;draft.locator=$('#note-locator').value;}
function persistDraft(){captureDraft();const id=selected,copy=structuredClone(draft);dirty=true;saveState('正在保存草稿…');draftQueue=draftQueue.catch(()=>{}).then(()=>set('draft-'+id,copy)).then(()=>{dirty=false;saveState('草稿已保存在本机');}).catch(e=>{saveState('草稿未保存，请勿关闭',true);throw e;});return draftQueue;}
function renderList(){const query=$('#search').value.trim().toLowerCase(),allNotes=rows(journal,'note'),papers=rows(journal,'paper').filter(p=>(filter==='archived')===p.archived).filter(p=>[p.title,p.authors,p.source,p.tags,...allNotes.filter(n=>n.paperId===p.id&&!n.archived).flatMap(n=>[n.text,n.locator])].join(' ').toLowerCase().includes(query));
 $('#paper-list').innerHTML=papers.length?papers.map(p=>`<button class="paper-item ${selected===p.id?'selected':''}" data-paper="${esc(p.id)}"><span class="badge">${statuses[p.status]}</span><h3>${esc(p.title)}</h3><small>${esc([p.authors,p.year].filter(Boolean).join(' · ')||'尚未填写作者')} · ${allNotes.filter(n=>n.paperId===p.id&&!n.archived).length} 条笔记</small></button>`).join(''):'<div class="empty">'+(query?'没有找到匹配记录。':filter==='archived'?'归档文献会保留在这里。':'新建一篇文献，开始落笔。')+'</div>';
}
async function selectPaper(id){if(uploading)return toast('截图正在保存，请稍等');if(selected&&$('#note-text'))await persistDraft();await draftQueue;selected=id;noteFilter='all';draft=await get('draft-'+id)||{text:'',kind:'note',locator:'',images:[]};renderList();renderMain();await set('selected',id);}
function sourceLink(source){let value=source;if(/^10\.\d{4,9}\//.test(value))value='https://doi.org/'+value;try{const u=new URL(value);if(['https:','http:'].includes(u.protocol))return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(source)}</a>`;}catch{}return esc(source);}
function renderMain(){const p=activePaper();if(!p){$('#main').innerHTML=welcome;return;}
 $('#main').innerHTML=`<header class="paper-head"><div class="paper-head-top"><span class="eyebrow">READING / ${statuses[p.status]}</span><div class="row"><button id="edit-paper">编辑文献</button><button id="export-paper">导出笔记</button><button id="archive-paper">${p.archived?'恢复文献':'归档'}</button></div></div><h2>${esc(p.title)}</h2><div class="meta">${esc([p.authors,p.year].filter(Boolean).join(' · ')||'作者与年份尚未填写')}${p.source?'<br>'+sourceLink(p.source):''}</div><div class="tags">${p.tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div></header>${p.archived?'<div class="archived-banner">这篇文献已归档，笔记仍然保留。恢复后可以继续记录。</div>':`<section class="composer"><div class="composer-head"><h3>${draft.editId?'编辑笔记':'此刻，想记下什么？'}</h3><select id="note-kind" aria-label="笔记类型">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${draft.kind===k?'selected':''}>${v}</option>`).join('')}</select></div><textarea id="note-text" maxlength="100000" aria-label="笔记内容" placeholder="写下理解、摘录，或一个还没成形的想法…&#10;截图后可直接按 Ctrl + V 粘贴。">${esc(draft.text)}</textarea><div class="images" id="draft-images"></div><details class="locator" ${draft.locator?'open':''}><summary>添加出处或条件（可选）</summary><input id="note-locator" maxlength="2000" value="${esc(draft.locator)}" placeholder="如 p. 5，Fig. 3b；适用条件或待核实之处" aria-label="出处与条件"></details><div class="composer-foot"><div class="row"><label class="button">＋ 截图<input id="image-upload" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden></label><small>支持粘贴或拖入图片</small></div><div class="row">${draft.editId?'<button id="cancel-edit">取消编辑</button>':''}<button class="primary" id="save-note">${draft.editId?'保存修改':'保存笔记'}</button></div></div><div class="draft-info" id="draft-info">文字草稿自动保存在本机；点击保存笔记后加入记录并参与同步。</div></section>`}<nav class="note-tabs" aria-label="笔记筛选">${[['all','全部记录'],...Object.entries(labels),['archived','已归档笔记']].map(([k,v])=>`<button data-note-filter="${k}" class="${noteFilter===k?'active':''}">${v}</button>`).join('')}</nav><div id="notes"></div>`;
 renderNotes();renderDraftImages();
}
function renderNotes(){const notes=rows(journal,'note').filter(n=>n.paperId===selected&&(noteFilter==='archived'?n.archived:!n.archived&&(noteFilter==='all'||n.kind===noteFilter)));$('#notes').innerHTML=notes.length?notes.map(n=>`<article class="note-card" data-note="${esc(n.id)}"><div class="note-top"><span class="badge ${n.kind}">${labels[n.kind]}</span><time>${new Date(n.updatedAt).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div>${n.text?`<p class="note-text">${esc(n.text)}</p>`:''}<div class="images">${n.images.map(id=>`<div class="image-wrap"><img data-image="${id}" alt="笔记截图，点击放大" tabindex="0" role="button"></div>`).join('')}</div>${n.locator?`<p class="note-source">出处 / 条件：${esc(n.locator)}</p>`:''}<div class="note-actions">${!n.archived?'<button data-edit-note="'+esc(n.id)+'">编辑</button>':''}<button data-archive-note="${esc(n.id)}">${n.archived?'恢复':'归档'}</button></div></article>`).join(''):'<div class="empty">'+(noteFilter==='all'?'还没有笔记。先记下最值得留下的那一点。':'这个分类还没有记录。')+'</div>';void loadImages($('#notes'));}
async function loadImages(container){if(!container)return;for(const img of container.querySelectorAll('img[data-image]')){const value=await get(img.dataset.image,'assets');if(value)img.src=value;else img.alt='截图暂未下载，请完成同步';}}
function renderDraftImages(){const box=$('#draft-images');if(!box)return;box.innerHTML=draft.images.map((id,i)=>`<div class="image-wrap"><img data-image="${id}" alt="待保存截图" tabindex="0" role="button"><button data-remove-image="${i}" aria-label="移除此截图">×</button></div>`).join('');void loadImages(box);}
async function addImages(files){if(!selected||!$('#note-text')||uploading)return;if(draft.images.length+files.length>20)throw Error('每条笔记最多 20 张截图，请分成多条记录');uploading=true;$('#save-note').disabled=true;saveState('正在保存截图…');try{for(const file of files){const id=await storeImage(file);if(!draft.images.includes(id))draft.images.push(id);await persistDraft();}renderDraftImages();toast('截图已加入草稿');}finally{uploading=false;if($('#save-note'))$('#save-note').disabled=false;}}
function paperDialog(p){editingPaper=p?.id||null;paperBaseHeads=p?heads(journal,'paper',p.id).map(e=>e.id).sort().join():undefined;const f=$('#paper-form');f.reset();for(const key of ['title','authors','year','source','tags','status'])if(p)f.elements[key].value=p[key];$('#paper-dialog-title').textContent=p?'编辑文献':'新建文献';$('#paper-dialog').showModal();f.elements.title.focus();}
async function saveNote(){if(uploading||saving)return;captureDraft();if(!draft.text.trim()&&!draft.images.length)throw Error('先写一点内容，或添加一张截图');const id=selected,copy=structuredClone(draft);$('#save-note').disabled=true;saving=true;try{await draftQueue;if(copy.editId){const current=heads(await snapshot(),'note',copy.editId).map(e=>e.id).sort().join();if(current!==copy.baseHeads)throw Error('这条笔记在其他页面或电脑已更新。草稿已保留，请先核对最新版本');}await put('note',{id:copy.editId||crypto.randomUUID(),paperId:id,text:copy.text,kind:copy.kind,locator:copy.locator,images:copy.images,archived:false},false,copy.editId?copy.baseHeads:undefined);draft={text:'',kind:'note',locator:'',images:[]};await set('draft-'+id,draft);journal=await snapshot();renderList();renderMain();saveState('已保存在本机');toast('笔记已保存');}finally{saving=false;if($('#save-note'))$('#save-note').disabled=false;}}
async function editNote(id){if(uploading)return;if(draft.text.trim()||draft.images.length){if(!confirm('当前草稿将被替换为这条笔记，是否继续？'))return;}const n=rows(journal,'note').find(n=>n.id===id);draft={text:n.text,kind:n.kind,locator:n.locator,images:[...n.images],editId:id,baseHeads:heads(journal,'note',id).map(e=>e.id).sort().join()};await draftQueue;await set('draft-'+selected,draft);renderMain();$('#note-text').focus();}
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportPaper(){const p=activePaper(),notes=rows(journal,'note').filter(n=>n.paperId===p.id&&!n.archived);let body=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${esc(p.title)}</title><style>body{max-width:850px;margin:40px auto;padding:20px;font:16px/1.9 sans-serif;color:#293d34}article{border-top:1px solid #ddd;padding:20px 0}img{max-width:100%}p{white-space:pre-wrap}small{color:#777}</style><h1>${esc(p.title)}</h1><p>${esc([p.authors,p.year,p.source,p.tags].filter(Boolean).join('\n'))}</p>`;for(const n of notes){body+=`<article><h2>${labels[n.kind]}</h2><p>${esc(n.text)}</p><small>${esc(n.locator)}</small>`;for(const id of n.images){const data=await get(id,'assets');if(!data)throw Error('有截图尚未同步，暂无法完整导出');body+=`<p><img src="${data}" alt="笔记截图"></p>`;}body+='</article>';}body+='</html>';download(body,p.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,80)+'-笔记.html','text/html');toast('已导出文字与截图，可用浏览器打开或打印');}
async function updateDataDialog(){vault=!!await get('vault');$('#sync-config').hidden=vault;$('#sync-connect').textContent=vault?'解锁自动同步':'连接并加密保存授权';$('#sync-state').textContent=syncMessage;const cs=conflicts(await snapshot());$('#conflicts').innerHTML=cs.length?'<h3>并行编辑的版本</h3><p>两个版本都已保留。选择后会形成新版本，原始历史仍可备份。</p>'+cs.map(c=>c.versions.map(e=>`<div><pre>${esc(e.value.title||e.value.text||'截图笔记')}${e.value.locator?'\n'+esc(e.value.locator):''}</pre><button data-resolve="${esc(e.id)}">使用此版本（${e.value.images?.length||0} 张截图）</button></div>`).join('')).join(''):'';}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-image]');if(!b)return;void run(async()=>{if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.paper){await selectPaper(b.dataset.paper);return;}if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();return;}if(b.dataset.noteFilter){noteFilter=b.dataset.noteFilter;document.querySelectorAll('[data-note-filter]').forEach(x=>x.classList.toggle('active',x===b));renderNotes();return;}if(b.dataset.image){const src=await get(b.dataset.image,'assets');if(!src)throw Error('截图尚未下载');$('#full-image').src=src;$('#image-dialog').showModal();return;}if(b.dataset.removeImage!==undefined){draft.images.splice(Number(b.dataset.removeImage),1);await persistDraft();renderDraftImages();return;}if(b.dataset.editNote){await editNote(b.dataset.editNote);return;}if(b.dataset.archiveNote){const n=rows(journal,'note').find(n=>n.id===b.dataset.archiveNote);await put('note',{...n,archived:!n.archived},false,heads(journal,'note',n.id).map(e=>e.id).sort().join());journal=await snapshot();renderNotes();renderList();return;}if(b.dataset.resolve){const d=await snapshot(),ev=d.events.find(v=>v.id===b.dataset.resolve);await put(ev.table,ev.value,true);await updateDataDialog();return;}
 switch(b.id){case 'new-paper':case 'first-paper':paperDialog();break;case 'edit-paper':paperDialog(activePaper());break;case 'save-note':await saveNote();break;case 'cancel-edit':draft={text:'',kind:'note',locator:'',images:[]};await draftQueue;await set('draft-'+selected,draft);renderMain();break;case 'archive-paper':{if(uploading)return;await persistDraft();const p=activePaper();await put('paper',{...p,archived:!p.archived},false,heads(journal,'paper',p.id).map(e=>e.id).sort().join());journal=await snapshot();renderList();renderMain();break;}case 'export-paper':await exportPaper();break;case 'data-open':await updateDataDialog();$('#data-dialog').showModal();break;case 'export-all':{b.disabled=true;try{await draftQueue;download(JSON.stringify(await exportBackup()),'paper-notebook-'+new Date().toISOString().slice(0,10)+'.json');$('#backup-state').textContent='完整备份已下载（未提交的草稿不包含在内）。';}finally{b.disabled=false;}break;}case 'sync-now':await synchronize();break;case 'sync-lock':lock();break;case 'sync-reset':lock();await set('vault',null);await updateDataDialog();break;}});});
$('#paper-form').addEventListener('submit',e=>{e.preventDefault();void run(async()=>{const f=e.target,old=editingPaper?rows(journal,'paper').find(p=>p.id===editingPaper):null,value={id:old?.id||crypto.randomUUID(),archived:old?.archived||false};for(const k of ['title','authors','year','source','tags','status'])value[k]=f.elements[k].value.trim();if(!value.title)throw Error('请填写文献题目');await put('paper',value,false,paperBaseHeads);journal=await snapshot();$('#paper-dialog').close();await selectPaper(value.id);toast('文献已保存');});});
document.addEventListener('input',e=>{if(e.target.id==='search')renderList();if(['note-text','note-kind','note-locator'].includes(e.target.id))void run(persistDraft);});
document.addEventListener('change',e=>{if(e.target.id==='image-upload'){const files=[...e.target.files];e.target.value='';void run(()=>addImages(files));}if(e.target.id==='import-all'){const file=e.target.files[0];e.target.value='';if(file)void run(async()=>{if(file.size>150*1024*1024)throw Error('备份超过 150 MB，请拆分或升级存储方案');$('#backup-state').textContent='正在校验与合并…';await importBackup(JSON.parse(await file.text()));journal=await snapshot();renderList();if(selected){captureDraft();renderMain();}$('#backup-state').textContent='备份已合并；已有版本保留，重复导入不会重复新增。';await updateDataDialog();});}});
document.addEventListener('paste',e=>{if(!e.target.closest('.composer'))return;const files=[...(e.clipboardData?.items||[])].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();void run(()=>addImages(files));}});
document.addEventListener('dragover',e=>{if(e.target.closest('.composer'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.target.closest('.composer')){e.preventDefault();void run(()=>addImages([...e.dataTransfer.files]));}});
document.addEventListener('keydown',e=>{if(e.target.matches('img[data-image]')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click();}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&e.target.closest('.composer')){e.preventDefault();void run(saveNote);}});
$('#sync-form').addEventListener('submit',e=>{e.preventDefault();void run(async()=>{const f=e.target,button=$('#sync-connect');button.disabled=true;try{if(vault)await unlock(f.elements.password.value);else{const c={owner:f.elements.owner.value.trim(),repo:f.elements.repo.value.trim()},secret=f.elements.token.value;await connect(c,secret);await remember(c,secret,f.elements.password.value);}f.elements.token.value='';f.elements.password.value='';await updateDataDialog();}finally{button.disabled=false;}});});
window.addEventListener('notebook-sync',()=>$('#sync-state').textContent=syncMessage);
window.addEventListener('notebook-remote',()=>void run(async()=>{journal=await snapshot();renderList();if(selected&&$('#notes'))renderNotes();if($('#data-dialog').open)await updateDataDialog();}));
window.addEventListener('beforeunload',e=>{if(dirty||uploading){e.preventDefault();e.returnValue='';}});
async function init(){if(!window.isSecureContext||!navigator.locks)throw Error('请使用现代浏览器，通过本地启动器或 HTTPS 网页打开');journal=await snapshot();selected=await get('selected');if(!rows(journal,'paper').some(p=>p.id===selected))selected=rows(journal,'paper').find(p=>!p.archived)?.id;draft=selected?await get('draft-'+selected)||draft:draft;renderList();if(selected)renderMain();saveState('本机自动保存');}
void init().catch(e=>{saveState('打开失败',true);toast(e.message,true);});
