
import {clean,pageHTML,pageText,imageIds,escape} from './progress/page.js';
import {get} from './store.js';
let editor,range,selected,notify=()=>{};
export const html=()=>editor?.isConnected?clean(editor.innerHTML):undefined;
export async function load(){const current=editor;for(const img of current?.querySelectorAll('img[data-image]')||[]){const src=await get(img.dataset.image,'assets');if(src)img.src=src;else img.alt='截图尚未下载，请同步';}}
function changed(){const text=document.querySelector('#note-text');text.value=pageText(clean(editor.innerHTML));text.dispatchEvent(new Event('input',{bubbles:true}));}
function insert(value){editor.focus();if(range&&editor.contains(range.commonAncestorContainer)){const s=getSelection();s.removeAllRanges();s.addRange(range);}document.execCommand('insertHTML',false,value);changed();}
export async function addImage(id){insert('<figure><img data-image="'+id+'" data-width="100" style="width:100%" alt="笔记截图"><figcaption>图片说明</figcaption></figure><p><br></p>');await load();window.dispatchEvent(new CustomEvent('notebook-image-added',{detail:{id}}));}
export function mount(draft){range=null;selected=null;const text=document.querySelector('#note-text');text.hidden=true;const toolbar=document.createElement('div');toolbar.className='page-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','笔记格式');toolbar.innerHTML='<button type="button" data-rich="bold">加粗</button><button type="button" data-block="h2">小标题</button><button type="button" data-block="p">正文</button><button type="button" data-rich="insertUnorderedList">列表</button><button type="button" data-rich-insert="todo">待办</button><button type="button" data-rich-insert="code">代码块</button><label class="resize-tools">图片宽度 <input id="paper-image-width" type="range" min="10" max="100" value="100" disabled aria-label="图片宽度滑块"><input id="paper-image-percent" type="number" min="10" max="100" value="100" disabled aria-label="图片宽度百分比">%</label>';
editor=document.createElement('div');editor.id='note-rich';editor.className='free-page';editor.contentEditable=String(!text.matches(':disabled'));editor.setAttribute('role','textbox');editor.setAttribute('aria-label','笔记正文');editor.setAttribute('aria-multiline','true');editor.innerHTML=pageHTML(draft);text.before(toolbar,editor);editor.addEventListener('input',changed);editor.addEventListener('paste',e=>{if([...e.clipboardData.files].some(f=>f.type.startsWith('image/')))return;e.preventDefault();e.stopPropagation();insert(escape(e.clipboardData.getData('text/plain')).replace(/\n/g,'<br>'));});
toolbar.addEventListener('mousedown',e=>{if(e.target.closest('button'))e.preventDefault();});toolbar.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||text.matches(':disabled'))return;if(b.dataset.richInsert){insert(b.dataset.richInsert==='todo'?'<p><span data-task="0" contenteditable="false" role="checkbox" aria-checked="false" tabindex="0">☐</span> 待办事项</p>':'<pre><code>在这里记录代码或计算参数</code></pre><p><br></p>');return;}editor.focus();if(range&&editor.contains(range.commonAncestorContainer)){getSelection().removeAllRanges();getSelection().addRange(range);}document.execCommand(b.dataset.block?'formatBlock':b.dataset.rich,false,b.dataset.block||null);changed();});
for(const input of toolbar.querySelectorAll('input'))input.addEventListener('input',()=>{if(!selected||!editor.contains(selected))return;const width=Number(input.value);if(!Number.isFinite(width)||width<10||width>100)return;selected.dataset.width=String(Math.round(width));selected.style.width=Math.round(width)+'%';for(const el of toolbar.querySelectorAll('input'))el.value=Math.round(width);changed();});
editor.addEventListener('click',e=>{const img=e.target.closest('img'),task=e.target.closest('[data-task]');if(img){e.stopPropagation();selected=img;for(const other of editor.querySelectorAll('img'))other.classList.toggle('image-selected',other===img);for(const el of toolbar.querySelectorAll('input')){el.disabled=false;el.value=img.dataset.width||100;}}if(task){e.stopPropagation();task.dataset.task=task.dataset.task==='1'?'0':'1';task.textContent=task.dataset.task==='1'?'☑':'☐';task.setAttribute('aria-checked',String(task.dataset.task==='1'));changed();}});editor.addEventListener('keydown',e=>{if(e.target.matches('[data-task]')&&[' ','Enter'].includes(e.key)){e.preventDefault();e.target.click();}});editor.addEventListener('dblclick',async e=>{if(e.target.matches('img[data-image]')){const src=await get(e.target.dataset.image,'assets');if(src){document.querySelector('#full-image').src=src;document.querySelector('#image-dialog').showModal();}}});void load();}
document.addEventListener('selectionchange',()=>{const s=getSelection();if(s.rangeCount&&editor?.contains(s.anchorNode))range=s.getRangeAt(0).cloneRange();});
