
const enc=new TextEncoder();export const bytes=s=>enc.encode(s).length;
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');
export const isParts=v=>v?.format==='workspace-parts-v1';
export async function decodeParts(m,root,read,cache){if(!isParts(root))return m.model.validate(root);if(root.module!==m.id||root.schemaVersion!==m.empty().schemaVersion||!Array.isArray(root.groups)||root.groups.length!==16||!Number.isSafeInteger(root.eventCount)||root.eventCount>100000)throw Error('分块索引格式错误');let count=0,total=0;const events=[];for(const group of root.groups){if(!Array.isArray(group)||group.length>4096)throw Error('分块索引超限');let text='';for(const p of group){if(!p||!/^([a-f0-9]{64})$/.test(p.hash)||!Number.isSafeInteger(p.bytes)||p.bytes<0||p.bytes>650000||++count>4096||(total+=p.bytes)>128000000)throw Error('分块信息异常');const key='sync-part:'+p.hash;let chunk=await cache.get(key);if(typeof chunk!=='string'||bytes(chunk)!==p.bytes||await hash(chunk)!==p.hash){const result=await read('workspace-parts/'+m.id+'/'+p.hash+'.json');if(!result)throw Error('同步分块缺失，本机记录保留');chunk=result.text;if(bytes(chunk)!==p.bytes||await hash(chunk)!==p.hash)throw Error('同步分块校验失败');await cache.set(key,chunk);}const value=JSON.parse(chunk);if(typeof value.text!=='string')throw Error('同步分块格式错误');text+=value.text;}if(text){const array=JSON.parse(text);if(!Array.isArray(array))throw Error('同步分块不是事件列表');events.push(...array);}}if(events.length!==root.eventCount)throw Error('同步分块记录数不一致');return m.model.validate({schemaVersion:root.schemaVersion,events});}
function bucket(e){let n=2166136261;for(const c of e.table+':'+e.key)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>28;}
export async function encodeParts(m,journal,previous,read,write,cache){
 const groups=Array.from({length:16},()=>[]),known=new Set(isParts(previous)?previous.groups.flat().map(p=>p.hash):[]);for(const e of journal.events)groups[bucket(e)].push(e);
 const plans=groups.map(group=>{if(!group.length)return [];const text=m.model.canonical(group.sort((a,b)=>a.id.localeCompare(b.id))),segments=[];function split(s){const v=JSON.stringify({text:s});if(bytes(v)>600000){const at=Math.floor(s.length/2);split(s.slice(0,at));split(s.slice(at));}else segments.push(v);}for(let at=0;at<text.length;at+=100000)split(text.slice(at,at+100000));return segments;});
 const all=plans.flat();if(all.length>4096||all.reduce((sum,s)=>sum+bytes(s),0)>128000000)throw Error('记录超过分块安全容量，请先导出全部备份');
 const output=[];for(const segments of plans){const parts=[];for(const segment of segments){const digest=await hash(segment),path='workspace-parts/'+m.id+'/'+digest+'.json';if(!known.has(digest)){const existing=await read(path);if(existing){if(await hash(existing.text)!==digest)throw Error('远端分块内容异常');}else{const r=await write(path,segment);if(!r.ok){if(![409,422].includes(r.status))throw Error('分块上传失败（'+r.status+'）');const latest=await read(path);if(!latest||await hash(latest.text)!==digest)throw Error('分块上传冲突，请重试');}}}await cache.set('sync-part:'+digest,segment);parts.push({hash:digest,bytes:bytes(segment)});}output.push(parts);}return {format:'workspace-parts-v1',module:m.id,schemaVersion:journal.schemaVersion,eventCount:journal.events.length,groups:output};}
