import {get,set,snapshot,receive,assetIds,imageId} from './store.js';
import {empty,validate,merge,canonical} from './model.js';
let token='',config,timer,busy=false,failures=0,inFlight;
export let syncMessage='尚未连接 · 本机记录可正常使用';
function status(message){syncMessage=message;window.dispatchEvent(new Event('notebook-sync'));}
function schedule(ms=3500){clearTimeout(timer);if(token&&config)timer=setTimeout(()=>void synchronize(),ms);}
const encode=s=>{let out='';for(const b of new TextEncoder().encode(s))out+=String.fromCharCode(b);return btoa(out);};
const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
async function request(path,init={}){return fetch('https://api.github.com'+path,{...init,redirect:'error',cache:'no-store',signal:AbortSignal.timeout(25000),headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,...init.headers}});}
async function checked(r){if(r.ok)return;throw Error(r.status===401?'授权已过期，请重新配置':r.status===403?'GitHub 拒绝访问或请求过于频繁':r.status===404?'仓库不存在或未授权':'同步请求失败（'+r.status+'）');}
async function privateRepo(c){const r=await request('/repos/'+c.owner+'/'+c.repo);await checked(r);const v=await r.json();if(v.private!==true||!v.permissions?.push)throw Error('仅允许连接具有写入权限的私有仓库');}
export async function connect(c,secret){if(busy)throw Error('同步中，请稍后再配置');if(!/^[a-zA-Z0-9-]+$/.test(c.owner)||!/^[a-zA-Z0-9_.-]+$/.test(c.repo)||!secret.trim())throw Error('请填写用户名、仓库与令牌');const old={config,token};config=c;token=secret.trim();try{await privateRepo(c);status('已连接，准备同步');schedule(100);}catch(e){config=old.config;token=old.token;throw e;}}
export function lock(){if(busy)throw Error('正在同步，请稍后再锁定');token='';config=undefined;clearTimeout(timer);status('同步已锁定 · 本机记录可正常使用');}
async function remoteFile(base,path){const r=await request(base+'/contents/'+path);if(r.status===404)return null;await checked(r);const f=await r.json();if(f.type!=='file'||f.encoding!=='base64'||f.size>850000)throw Error('同步文件超过容量或格式无效，本机记录仍保留');return {sha:f.sha,text:decode(f.content)};}
async function pushFile(base,path,text,sha){if(new TextEncoder().encode(text).length>850000)throw Error('同步历史超过 850 KB，请下载完整备份；本机记录仍正常保存');return request(base+'/contents/'+path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Sync paper notebook',content:encode(text),...(sha?{sha}:{})})});}
export function synchronize(){if(inFlight)return inFlight;inFlight=performSync().finally(()=>inFlight=undefined);return inFlight;}
async function performSync(){if(!token||!config||busy)return;busy=true;status('正在同步文献与截图…');try{await navigator.locks.request('paper-notebook-sync',async()=>{await privateRepo(config);const base='/repos/'+config.owner+'/'+config.repo;
 for(let attempt=0;attempt<3;attempt++){const file=await remoteFile(base,'notebook-v1.json'),remote=file?validate(JSON.parse(file.text)):empty(),local=await snapshot(),combined=merge(local,remote),remoteAssets=new Set(assetIds(remote));
 for(const id of assetIds(combined)){let data=await get(id,'assets');if(!data){const f=await remoteFile(base,'images/'+id+'.json');if(!f)throw Error('远端截图缺失，已暂停同步以保留完整性');data=JSON.parse(f.text);if(typeof data!=='string'||data.length>800000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data)||await imageId(data)!==id)throw Error('截图校验失败');await set(id,data,'assets');}
 if(!remoteAssets.has(id)){const existing=await remoteFile(base,'images/'+id+'.json');if(existing){if(await imageId(JSON.parse(existing.text))!==id)throw Error('远端截图校验失败');}else{const r=await pushFile(base,'images/'+id+'.json',JSON.stringify(data));if(r.status===409||r.status===422)throw Error('另一台电脑正在同步截图，稍后自动重试');await checked(r);}}}
 await receive(combined);const content=canonical(combined);if(file&&content===canonical(remote)){status('已同步 · '+new Date().toLocaleTimeString());return;}const r=await pushFile(base,'notebook-v1.json',content,file?.sha);if(r.status===409||r.status===422)continue;await checked(r);status('已同步 · '+new Date().toLocaleTimeString());return;}throw Error('其他电脑正在更新，稍后自动重试');});failures=0;}catch(e){failures++;status((e instanceof TypeError?'网络暂不可用':e.message)+' · 本机记录已保留');}finally{busy=false;schedule(Math.min(300000,30000*2**Math.min(failures,4)));}}
async function key(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function remember(c,secret,pass){if(pass.length<12)throw Error('解锁密码至少 12 个字符');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,salt),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(JSON.stringify({config:c,token:secret})));await set('vault',{salt:[...salt],iv:[...iv],data:[...new Uint8Array(data)]});}
export async function unlock(pass){const v=await get('vault');if(!v)throw Error('本机尚未保存授权');let secret;try{secret=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv)},await key(pass,new Uint8Array(v.salt)),new Uint8Array(v.data))));}catch{throw Error('解锁密码不正确');}await connect(secret.config,secret.token);}
window.addEventListener('notebook-local',()=>schedule());window.addEventListener('online',()=>schedule(100));window.addEventListener('focus',()=>schedule(100));
