import {modules} from './sync-registry.js';
import {get,set} from './store.js';
export {modules};
let credentials=null,inFlight=null,timer,failures=0;
export let results={};
export let message='全部同步 · 尚未解锁';
export const unlocked=()=>!!credentials;
export const running=()=>!!inFlight;
export const hasVault=async()=>!!await get('workspace-sync-vault');
function notify(){window.dispatchEvent(new Event('workspace-sync'));}
function schedule(delay=3500){clearTimeout(timer);if(credentials)timer=setTimeout(()=>void syncAll(),delay);}
async function derive(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:new Uint8Array(salt),iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function decrypt(v,pass){try{return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv)},await derive(pass,v.salt),new Uint8Array(v.data))));}catch{throw Error('解锁密码不正确，或授权文件已损坏');}}
async function encrypt(value,pass){if(pass.length<12)throw Error('统一解锁密码至少 12 个字符');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(pass,salt);const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(value)));return {salt:[...salt],iv:[...iv],data:[...new Uint8Array(data)]};}
function checkCredentials(value){for(const m of modules){const c=value?.[m.id];if(!c||!/^[a-zA-Z0-9-]+$/.test(c.owner)||!/^[a-zA-Z0-9_.-]+$/.test(c.repo)||typeof c.token!=='string'||!c.token.trim())throw Error(m.name+'：请填写正确的仓库和授权');}}
async function request(c,path='',init={}){return fetch('https://api.github.com/repos/'+c.owner+'/'+c.repo+path,{...init,redirect:'error',cache:'no-store',signal:AbortSignal.timeout(25000),headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+c.token,...init.headers}});}
async function checked(r){if(!r.ok)throw Error(r.status===401?'授权失效，请更新令牌':r.status===403?'没有权限或请求限流':r.status===404?'仓库不存在或令牌未授权该仓库':'GitHub 请求失败（'+r.status+'）');}
async function checkRepo(c){const r=await request(c);await checked(r);const v=await r.json();if(!v.private||!v.permissions?.push)throw Error('只能同步到有读写权限的私有仓库');}
export async function saveConfiguration(value,pass){if(inFlight)throw Error('请等待本轮同步完成');checkCredentials(value);const encrypted=await encrypt(value,pass);for(const m of modules){try{await checkRepo(value[m.id]);}catch(e){throw Error(m.name+'：'+e.message);}}await set('workspace-sync-vault',encrypted);credentials=structuredClone(value);message='已统一解锁';results={};notify();return syncAll();}
export async function unlockAll(pass){if(inFlight)throw Error('请等待本轮同步完成');const v=await get('workspace-sync-vault');if(!v)throw Error('请先设置统一同步');const value=await decrypt(v,pass);checkCredentials(value);credentials=value;message='已统一解锁';notify();return syncAll();}
export function lockAll(){if(inFlight)throw Error('同步尚未结束，请稍后锁定');credentials=null;clearTimeout(timer);message='全部同步 · 已锁定';notify();}
export async function legacyAvailability(){const out={};for(const m of modules)out[m.id]=!!await m.store.get(m.vault);return out;}
export async function importLegacy(passwords,newPass){if(inFlight)throw Error('请等待同步完成');const value={};for(const m of modules){const v=await m.store.get(m.vault);if(!v){if(m.id==='progress'&&value.paper){value.progress={...value.paper};continue;}throw Error(m.name+'尚无原授权，请使用新令牌配置');}try{const old=await decrypt(v,passwords[m.id]||'');value[m.id]={...old.config,token:old.token};}catch(e){throw Error(m.name+'：'+e.message);}}return saveConfiguration(value,newPass);}
const encode=s=>{let out='';for(const b of new TextEncoder().encode(s))out+=String.fromCharCode(b);return btoa(out);};
const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
async function read(c,path,max=850000){const r=await request(c,'/contents/'+path);if(r.status===404)return null;await checked(r);const f=await r.json();if(f.type!=='file'||f.encoding!=='base64'||f.size>max)throw Error('同步文件过大或格式异常');const text=decode(f.content);if(new TextEncoder().encode(text).length>max)throw Error('同步文件超过容量');return {sha:f.sha,text};}
async function write(c,path,text,sha){if(new TextEncoder().encode(text).length>850000)throw Error('同步历史超过 850 KB，请先下载备份');return request(c,'/contents/'+path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Sync workspace records',content:encode(text),...(sha?{sha}:{})})});}
async function syncModule(m,c){await checkRepo(c);if(m.id==='english')await m.store.set('sync-target',{owner:c.owner,repo:c.repo});return navigator.locks.request(m.lock,async()=>{for(let i=0;i<3;i++){const file=await read(c,m.file),remote=file?m.model.validate(JSON.parse(file.text)):m.empty();let combined=m.model.merge(await m.store.snapshot(),remote);
 if(m.store.assetIds){for(const id of m.store.assetIds(combined)){let data=await m.store.get(id,'assets');const path='images/'+id+'.json';if(!data){const f=await read(c,path);if(!f)throw Error('远端截图缺失，已停止该模块同步');data=JSON.parse(f.text);if(typeof data!=='string'||data.length>800000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data)||await m.store.imageId(data)!==id)throw Error('截图校验失败');await m.store.set(id,data,'assets');}if(!m.store.assetIds(remote).includes(id)){const f=await read(c,path);if(f){if(await m.store.imageId(JSON.parse(f.text))!==id)throw Error('远端截图校验失败');}else{const r=await write(c,path,JSON.stringify(data));if(r.status===409||r.status===422){const latest=await read(c,path);if(!latest||await m.store.imageId(JSON.parse(latest.text))!==id)throw Error('截图并行更新，请重试');}else await checked(r);}}}}
 await m.store.receive(combined);const content=m.model.canonical(combined);if(m.model.canonical(await m.store.snapshot())!==content)continue;if(!file||content!==m.model.canonical(remote)){const r=await write(c,m.file,content,file?.sha);if(r.status===409||r.status===422)continue;await checked(r);}if(m.model.canonical(await m.store.snapshot())!==content)continue;const conflictCount=m.model.conflicts(await m.store.snapshot()).length;return {ok:true,conflictCount,at:Date.now()};}throw Error('记录正在更新，请稍后再同步');});}
async function englishReceipts(c){const warnings=[];for(const name of ['dictionary-status','maimemo-status']){try{const f=await read(c,name+'.json',name==='maimemo-status'?1000000:850000);const v=f?JSON.parse(f.text):null;if(v&&(v.schemaVersion!==1||!v.records||typeof v.records!=='object'||Array.isArray(v.records)))throw Error('状态格式异常');await modules.find(m=>m.id==='english').store.set(name,v?{...v,fetchedAt:Date.now()}:null);}catch{warnings.push(name==='dictionary-status'?'查词回执暂未刷新':'墨墨回执暂未刷新');}}window.dispatchEvent(new Event('unified-english-status'));window.dispatchEvent(new Event('coach-maimemo'));return warnings;}
export function syncAll(){if(inFlight)return inFlight;if(!credentials){message='请先统一解锁';notify();return Promise.resolve();}clearTimeout(timer);const current=structuredClone(credentials);inFlight=(async()=>{message='正在同步全部模块…';notify();for(const m of modules){results[m.id]={pending:true};notify();try{results[m.id]=await syncModule(m,current[m.id]);if(m.id==='english')results[m.id].warnings=await englishReceipts(current[m.id]);}catch(e){results[m.id]={ok:false,error:e instanceof TypeError?'网络暂不可用':e.message};}notify();}const failed=modules.filter(m=>!results[m.id]?.ok).length,conflicted=modules.filter(m=>results[m.id]?.conflictCount).length,warned=modules.some(m=>results[m.id]?.warnings?.length);message=failed?`${failed} 个模块未完成 · 可重试`:conflicted?'同步完成 · 有并行版本待处理':warned?'记录已同步 · 部分回执待刷新':'全部已同步 · '+new Date().toLocaleTimeString();failures=failed?failures+1:0;notify();})().finally(()=>{inFlight=null;notify();schedule(Math.min(300000,30000*2**Math.min(failures,4)));});return inFlight;}
export async function resolve(moduleId,eventId){const m=modules.find(m=>m.id===moduleId);if(!m)throw Error('未知模块');if(m.store.resolveVersion)await m.store.resolveVersion(eventId);else{const d=await m.store.snapshot(),e=d.events.find(v=>v.id===eventId);if(!e)throw Error('版本不存在');await m.store.put(e.table,e.value,true);}return syncAll();}
for(const event of ['notebook-local','coach-local'])window.addEventListener(event,()=>schedule());for(const event of ['online','focus'])window.addEventListener(event,()=>schedule(100));
