import * as sync from './unified-engine.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./unified-sync.css',import.meta.url);document.head.append(style);
const bar=document.createElement('section');bar.className='unified-bar';bar.innerHTML='<span id="workspace-sync-status" role="status">全部同步 · 尚未解锁</span><div><button id="workspace-sync-now">全部同步</button><button id="workspace-sync-settings">同步设置</button></div>';
document.querySelector('.module-nav')?.after(bar);
const dialog=document.createElement('dialog');dialog.id='workspace-sync-dialog';dialog.className='unified-dialog';dialog.innerHTML=`<div class="unified-heading"><h2>全部模块同步</h2><button id="workspace-sync-close" aria-label="关闭同步设置">×</button></div><p>一次解锁，同步本机已保存的所有模块记录。草稿只在本机保存。授权加密保存在当前浏览器；刷新页面后需重新解锁。</p><div id="workspace-results" aria-live="polite"></div><p id="workspace-error" role="alert"></p><form id="workspace-quick" hidden><label>原英语学习同步密码<input name="password" type="password" autocomplete="current-password" required></label><p>自动沿用已有授权，并将这个密码用作全部模块的统一解锁密码。</p><button type="submit">沿用英语密码并全部同步</button></form><form id="workspace-unlock" hidden><label>统一解锁密码<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">解锁并全部同步</button></form><div class="unified-actions"><button id="workspace-lock">锁定全部同步</button><button id="workspace-reconfigure">配置或更新授权</button></div><section id="workspace-setup" hidden><h3>使用一个 GitHub 令牌</h3><p>令牌需同时授权下列私有仓库，Contents 选择 Read and write。请保留原来的仓库名称；英语查词、墨墨任务仍在原英语仓库运行。</p><form id="workspace-config"><label>GitHub 用户名<input name="owner" value="jiangyimin123456" required></label>${sync.modules.map(m=>`<label>${m.name} · 私有仓库<input name="${m.id}" value="${m.repo}" required></label>`).join('')}<label>Fine-grained token<input name="token" type="password" autocomplete="off" required></label><label>设置统一解锁密码（至少 12 位）<input name="password" type="password" autocomplete="new-password" minlength="12" required></label><label>再次输入密码<input name="confirm" type="password" autocomplete="new-password" minlength="12" required></label><button type="submit">保存授权并全部同步</button></form><details id="workspace-legacy"><summary>已分别配置过？导入原有授权</summary><p>只需这一次输入各模块原解锁密码，然后设一个统一密码。原授权和数据不会删除。课题进展若尚未配置，会沿用文献笔记的仓库与授权。</p><form id="workspace-import">${sync.modules.map(m=>`<label data-legacy-module="${m.id}">${m.name}原解锁密码<input name="${m.id}" type="password" autocomplete="off"></label>`).join('')}<label>新的统一解锁密码<input name="password" type="password" minlength="12" required autocomplete="new-password"></label><label>再次输入密码<input name="confirm" type="password" minlength="12" required autocomplete="new-password"></label><button type="submit">导入授权并全部同步</button></form></details></section><section id="workspace-conflicts"></section>`;document.body.append(dialog);
const $=s=>document.querySelector(s);let working=false,renderNumber=0;
async function action(fn){if(working)return;working=true;$('#workspace-error').textContent='';disable();try{await fn();}catch(e){$('#workspace-error').textContent=e.message;if(!dialog.open)dialog.showModal();}finally{working=false;disable();await refresh();}}
function disable(){for(const el of dialog.querySelectorAll('button,input'))el.disabled=working||sync.running();$('#workspace-sync-now').disabled=working||sync.running();$('#workspace-sync-close').disabled=false;}
async function refresh(){const revision=++renderNumber;$('#workspace-sync-status').textContent=sync.message;$('#workspace-results').innerHTML=sync.modules.map(m=>{const r=sync.results[m.id];const text=!r?'等待同步':r.pending?'同步中…':r.ok?(r.conflictCount?`记录已传输，${r.conflictCount} 项并行版本待处理`:'已同步')+(r.warnings?.length?' · '+r.warnings.join('；'):''):r.error+' · 本机记录保留';return `<p><b>${m.name}</b><span>${esc(text)}</span></p>`;}).join('');const legacy=await sync.legacyAvailability();$('#workspace-quick').hidden=sync.unlocked()||!legacy.english;$('#workspace-unlock').hidden=sync.unlocked()||legacy.english||!await sync.hasVault();disable();if(!dialog.open)return;let html='';for(const m of sync.modules){for(const c of m.model.conflicts(await m.store.snapshot()))html+=`<h3>${m.name} · 并行版本</h3><p>所有版本均保留，请核对后选择。</p>`+c.versions.map(v=>`<pre>${esc(JSON.stringify(v.value,null,2))}</pre><button data-workspace-resolve="${esc(v.id)}" data-module="${m.id}">使用此版本</button>`).join('');}if(revision===renderNumber)$('#workspace-conflicts').innerHTML=html;}
async function open(){await refresh();const exists=await sync.hasVault();$('#workspace-setup').hidden=exists;const legacy=await sync.legacyAvailability();if(legacy.english)$('#workspace-setup').hidden=true;for(const m of sync.modules){const input=$(`#workspace-import [name=${m.id}]`);input.required=legacy[m.id];input.closest('label').hidden=!legacy[m.id];}if(!dialog.open)dialog.showModal();await refresh();}
$('#workspace-sync-settings').onclick=()=>void action(open);$('#workspace-sync-now').onclick=()=>void action(async()=>{if(sync.unlocked())await sync.syncAll();else await open();});$('#workspace-sync-close').onclick=()=>dialog.close();$('#workspace-lock').onclick=()=>void action(()=>sync.lockAll());$('#workspace-reconfigure').onclick=()=>{$('#workspace-setup').hidden=!$('#workspace-setup').hidden;};
$('#workspace-quick').onsubmit=e=>{e.preventDefault();const f=e.target,pass=f.elements.password.value;f.reset();void action(()=>sync.useEnglishPassword(pass));};
$('#workspace-unlock').onsubmit=e=>{e.preventDefault();const f=e.target,pass=f.elements.password.value;f.reset();void action(()=>sync.unlockAll(pass));};
$('#workspace-config').onsubmit=e=>{e.preventDefault();const f=e.target;if(f.elements.password.value!==f.elements.confirm.value){$('#workspace-error').textContent='两次密码不一致';return;}const pass=f.elements.password.value,token=f.elements.token.value.trim(),owner=f.elements.owner.value.trim();const value=Object.fromEntries(sync.modules.map(m=>[m.id,{owner,repo:f.elements[m.id].value.trim(),token}]));void action(async()=>{await sync.saveConfiguration(value,pass);f.elements.token.value='';f.elements.password.value='';f.elements.confirm.value='';$('#workspace-setup').hidden=true;});};
$('#workspace-import').onsubmit=e=>{e.preventDefault();const f=e.target;if(f.elements.password.value!==f.elements.confirm.value){$('#workspace-error').textContent='两次密码不一致';return;}const passwords=Object.fromEntries(sync.modules.map(m=>[m.id,f.elements[m.id].value])),pass=f.elements.password.value;f.reset();void action(async()=>{await sync.importLegacy(passwords,pass);$('#workspace-setup').hidden=true;});};
dialog.addEventListener('click',e=>{const b=e.target.closest('[data-workspace-resolve]');if(b)void action(()=>sync.resolve(b.dataset.module,b.dataset.workspaceResolve));});
// Legacy local-backup dialogs remain available; sync actions now have one entry point.
const backupButton=$('#data-open');if(backupButton)backupButton.textContent='本模块备份';const backupTitle=$('#data-dialog .dialog-heading h2');if(backupTitle)backupTitle.textContent='本模块备份';const oldSync=$('#sync-form')?.closest('section');if(oldSync){oldSync.hidden=true;const help=document.createElement('p');help.textContent='跨电脑同步请使用页面顶部的“全部同步”。';oldSync.after(help);}
window.addEventListener('workspace-sync',()=>void refresh());
window.addEventListener('workspace-sync',()=>{const oldStatus=$('#sync-top');if(oldStatus)oldStatus.textContent=sync.message;});
void refresh();
