
import * as paper from './store.js';
import * as progress from './progress/store.js';
import {rows} from './model.js';
import {pageHTML,escape} from './progress/page.js';
const isProgress=location.pathname.includes('/progress/'),moduleId=isProgress?'progress':'paper',store=isProgress?progress:paper;
const api=(await import(isProgress?'./progress/progress.js':'./notebook.js')).studioAPI;
const root=new URL('./',import.meta.url),$=s=>document.querySelector(s);
function report(error){const toast=$('#toast');toast.textContent=error.message;toast.style.display='block';setTimeout(()=>toast.style.display='none',6500);}
const run=fn=>Promise.resolve().then(fn).catch(report);
const tools=document.createElement('div');tools.className='workspace-tools';tools.innerHTML='<button id="all-search">搜索全部笔记</button><button id="note-history">历史版本</button>'+(!isProgress?'<button id="note-pin">置顶 / 取消置顶</button>':'');$('.topbar').after(tools);
const statuses=document.createElement('div');statuses.className='save-statuses';statuses.setAttribute('role','status');statuses.innerHTML='<span id="local-detail"></span><span id="cloud-detail"></span>';tools.append(statuses);
function status(){const id=api.current();$('#note-history').disabled=!id;if($('#note-pin'))$('#note-pin').disabled=!id;const local=$('#save-state')?.textContent||'等待编辑';$('#local-detail').textContent='本机：'+(/正在|失败|请勿/.test(local)?local:api.state());$('#cloud-detail').textContent='云端：'+($('#workspace-sync-status')?.textContent||'尚未解锁')+'（不含草稿）';}
for(const el of [$('#save-state'),$('#workspace-sync-status')].filter(Boolean))new MutationObserver(status).observe(el,{childList:true,subtree:true,characterData:true});status();
const dialog=document.createElement('dialog');dialog.id='global-search';dialog.innerHTML='<div class="dialog-heading"><h2>搜索文献与课题笔记</h2><button id="search-close" aria-label="关闭搜索">×</button></div><input id="global-query" type="search" placeholder="搜索标题、DOI、正文、标签或计算结果" aria-label="搜索全部笔记"><div class="row"><select id="search-scope" aria-label="模块范围"><option value="all">全部模块</option><option value="paper">文献笔记</option><option value="progress">课题进展</option></select><label><input id="search-archived" type="checkbox">包含归档</label></div><p class="meta">搜索本机已保存的记录；其他电脑的新内容需先同步。</p><div id="global-results"></div>';document.body.append(dialog);$('#search-close').onclick=()=>dialog.close();
async function allNotes(){const result=[];for(const [id,st,name] of [['paper',paper,'文献笔记'],['progress',progress,'课题进展']]){const d=await st.snapshot(),parents=new Map(rows(d,'paper').map(p=>[p.id,p]));for(const n of rows(d,'note')){const p=parents.get(n.paperId);result.push({module:id,name,n,parent:p?.title||'随手记',archived:n.archived||p?.archived,title:n.title||n.text.trim().split('\n')[0].slice(0,100)||'截图笔记',body:[p?.title,p?.source,n.title,n.text,n.source,n.locator,n.result,n.plan,n.ref,...(n.tags||[]),...(n.ai?.tags||[]),n.ai?.ocr].filter(Boolean).join(' · ')});}}return result;}
function mark(text,query){if(!query)return escape(text);const lower=text.toLowerCase(),q=query.toLowerCase();let result='',offset=0,index;while((index=lower.indexOf(q,offset))!==-1){result+=escape(text.slice(offset,index))+'<mark>'+escape(text.slice(index,index+q.length))+'</mark>';offset=index+q.length;}return result+escape(text.slice(offset));}
let generation=0;
async function search(){const g=++generation,q=$('#global-query').value.trim(),scope=$('#search-scope').value,archived=$('#search-archived').checked;const all=await allNotes(),recent=await paper.get('studio-recent')||[];if(g!==generation)return;const notes=all.filter(x=>(scope==='all'||x.module===scope)&&(archived||!x.archived)&&x.body.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>Number(!!b.n.pinned)-Number(!!a.n.pinned)||(q?b.n.updatedAt-a.n.updatedAt:(recent.findIndex(x=>x.module===a.module&&x.id===a.n.id)+1||999)-(recent.findIndex(x=>x.module===b.module&&x.id===b.n.id)+1||999)));$('#global-results').innerHTML='<p class="meta">'+notes.length+' 条匹配'+(notes.length>100?'，先显示前 100 条':'')+'</p>'+notes.slice(0,100).map(x=>{const at=x.body.toLowerCase().indexOf(q.toLowerCase()),start=Math.max(0,at-45),snippet=x.body.slice(start,start+230);return '<button class="search-result" data-open-note="'+escape(x.n.id)+'" data-module="'+x.module+'"><strong>'+ (x.n.pinned?'★ ':'')+mark(x.title,q)+'</strong><small>'+escape(x.name+' / '+x.parent)+(x.archived?' · 已归档':'')+'</small><span>'+mark((start?'…':'')+snippet,q)+'</span></button>';}).join('');}
$('#all-search').onclick=()=>run(async()=>{await api.persist();dialog.showModal();await search();$('#global-query').focus();});for(const el of [$('#global-query'),$('#search-scope'),$('#search-archived')])el.addEventListener('input',()=>run(search));
async function open(id,mod){await api.persist();if(mod===moduleId){await api.open(id);dialog.close();}else{const url=new URL(mod==='progress'?'progress/':'./',root);url.searchParams.set('note',id);location.assign(url.href);}}
$('#global-results').onclick=e=>{const b=e.target.closest('[data-open-note]');if(b)run(()=>open(b.dataset.openNote,b.dataset.module));};
const recentBox=document.createElement('details');recentBox.className='studio-recent';recentBox.innerHTML='<summary>最近打开（本机）</summary><div></div>';$('.library-foot').before(recentBox);
let last='',recentQueue=Promise.resolve();
async function recentRender(){const entries=await paper.get('studio-recent')||[],all=await allNotes();recentBox.querySelector('div').innerHTML=entries.map(e=>all.find(n=>n.module===e.module&&n.n.id===e.id)).filter(Boolean).slice(0,10).map(n=>'<button class="note-nav" data-recent="'+escape(n.n.id)+'" data-module="'+n.module+'">'+escape(n.title)+'<small>'+n.name+'</small></button>').join('')||'<p class="muted">打开笔记后显示在这里</p>';}
recentBox.onclick=e=>{const b=e.target.closest('[data-recent]');if(b)run(()=>open(b.dataset.recent,b.dataset.module));};
function opened(){status();const id=api.current();if(id&&id!==last){last=id;recentQueue=recentQueue.then(async()=>{const old=await paper.get('studio-recent')||[];await paper.set('studio-recent',[{module:moduleId,id},...old.filter(x=>x.module!==moduleId||x.id!==id)].slice(0,20));await recentRender();}).catch(report);}}
window.addEventListener('studio-note-open',opened);window.addEventListener('notebook-remote',()=>run(recentRender));void run(recentRender);
const history=document.createElement('dialog');history.id='history-dialog';history.innerHTML='<div class="dialog-heading"><h2>笔记历史版本</h2><button id="history-close" aria-label="关闭历史">×</button></div><p class="meta">选择版本预览。载入为草稿后，检查并点击保存才会生成新版本；原历史继续保留。</p><select id="history-select" aria-label="历史版本"></select><div id="history-preview" class="free-page"></div><button id="history-restore" class="primary">载入此版本为草稿</button>';document.body.append(history);$('#history-close').onclick=()=>history.close();let versions=[],previewGeneration=0;
async function preview(){const g=++previewGeneration,v=versions[Number($('#history-select').value)]?.value;if(!v)return;const area=$('#history-preview');area.innerHTML='<h3>'+escape(v.title||'笔记正文')+'</h3>'+pageHTML(v)+'<p>'+escape([v.source,v.locator].filter(Boolean).join(' · '))+'</p>';for(const img of area.querySelectorAll('img[data-image]')){const src=await store.get(img.dataset.image,'assets');if(g!==previewGeneration)return;if(src)img.src=src;else img.alt='截图尚未同步到本机';}}
$('#note-history').onclick=()=>run(async()=>{await api.persist();const id=api.current();versions=(await store.snapshot()).events.filter(e=>e.table==='note'&&e.key===id).sort((a,b)=>b.at-a.at||b.id.localeCompare(a.id));const recovery=await store.get('before-history-restore-'+id);if(recovery)versions.push({at:0,value:recovery,recovery:true});$('#history-select').innerHTML=versions.map((e,i)=>'<option value="'+i+'">'+(e.recovery?'上次恢复前保留的草稿':new Date(e.at).toLocaleString()+' · '+(i===0?'最近保存':'历史版本')+' #'+(versions.length-i))+'</option>').join('');$('#history-restore').disabled=!versions.length;history.showModal();await preview();});$('#history-select').onchange=()=>run(preview);$('#history-restore').onclick=()=>run(async()=>{const v=versions[Number($('#history-select').value)]?.value;if(v){await api.restore(v);history.close();opened();}});
if($('#note-pin'))$('#note-pin').onclick=()=>run(async()=>{await api.pin();await recentRender();});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();if(!document.querySelector('dialog[open]'))$('#all-search').click();}});
const wanted=new URL(location.href).searchParams.get('note');if(wanted){let attempts=0;const check=setInterval(()=>{if($('#note-text')||$('#page-editor')||$('#first-project')){clearInterval(check);run(async()=>{await api.open(wanted);const url=new URL(location.href);url.searchParams.delete('note');window.history.replaceState(null,'',url);});}else if(++attempts>100)clearInterval(check);},100);}opened();
