import {modules} from './sync-registry.js';
const names={paper:'paper-notebook-v1',progress:'research-progress-v1',english:'english-notebook-local-v1'};
const allowed=k=>typeof k==='string'&&(k==='stream-draft'||k==='workspace-draft'||/^(paper-draft-|note-draft-|new-draft-|draft-|page-draft-|new-page-|before-history-restore-)/.test(k));
async function database(m){await m.store.snapshot();return new Promise((resolve,reject)=>{const r=indexedDB.open(names[m.id],1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function capture(m){const db=await database(m);try{return await new Promise((resolve,reject)=>{const tx=db.transaction([...db.objectStoreNames]),ds=tx.objectStore('data'),keys=ds.getAllKeys(),values=ds.getAll(),ak=db.objectStoreNames.contains('assets')?tx.objectStore('assets').getAllKeys():null,av=ak?tx.objectStore('assets').getAll():null;tx.oncomplete=()=>{const data=Object.fromEntries(keys.result.map((k,i)=>[k,values.result[i]]));resolve({journal:data.journal||m.empty(),drafts:Object.fromEntries(Object.entries(data).filter(([k,v])=>allowed(k)&&v!=null)),assets:Object.fromEntries((ak?.result||[]).map((k,i)=>[k,av.result[i]]))});};tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
function refs(value){return [...new Set(JSON.stringify(value).match(/img-[a-f0-9]{64}/g)||[])];}
export async function exportWorkspace(){await window.workspaceFlush?.();const result={format:'workspace-backup-v1',createdAt:new Date().toISOString(),modules:{},recovery:await modules[0].store.get('workspace-restored-drafts')||[]};for(const m of modules){const x=await capture(m);m.model.validate(x.journal);const assets={};for(const id of refs([x.journal,x.drafts,result.recovery.filter(r=>r.module===m.id)])){const data=x.assets[id];if(!data||await m.store.imageId?.(data)!==id)throw Error(m.name+'有图片未下载，先同步后再备份');assets[id]=data;}result.modules[m.id]={journal:x.journal,drafts:x.drafts,assets};}return result;}
export async function importWorkspace(input){if(input?.format!=='workspace-backup-v1'||!input.modules)throw Error('请选择全模块备份文件');if(input.recovery!==undefined&&(!Array.isArray(input.recovery)||input.recovery.some(r=>!r||!modules.some(m=>m.id===r.module)||!allowed(r.key))))throw Error('恢复草稿结构无效');const incoming=[];for(const m of modules){const x=input.modules[m.id];if(!x||!x.drafts||!x.assets||Array.isArray(x.drafts)||Array.isArray(x.assets))throw Error(m.name+'备份结构缺失');m.model.validate(x.journal);m.model.merge(await m.store.snapshot(),x.journal);if(Object.keys(x.drafts).some(k=>!allowed(k)))throw Error('备份包含不支持的草稿字段');for(const id of refs([x.journal,x.drafts,(input.recovery||[]).filter(r=>r.module===m.id)])){const data=x.assets[id];if(typeof data!=='string'||data.length>800000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data)||await m.store.imageId?.(data)!==id)throw Error(m.name+'图片缺失或校验失败，尚未恢复任何数据');}incoming.push([m,x]);}
// Validate all modules before the first write; merge histories, never replace them.
const recovery=await modules[0].store.get('workspace-restored-drafts')||[];let drafts=0;for(const [m,x]of incoming){for(const id of refs([x.journal,x.drafts,(input.recovery||[]).filter(r=>r.module===m.id)]))await m.store.set(id,x.assets[id],'assets');await m.store.receive(x.journal);for(const [key,value]of Object.entries(x.drafts)){const old=await m.store.get(key);if(old==null)await m.store.set(key,value);else if(JSON.stringify(old)!==JSON.stringify(value))recovery.push({module:m.id,key,value,at:input.createdAt});drafts++;}}
for(const r of input.recovery||[]){if(r&&modules.some(m=>m.id===r.module)&&allowed(r.key)&&!recovery.some(v=>JSON.stringify(v)===JSON.stringify(r)))recovery.push(r);}await modules[0].store.set('workspace-restored-drafts',recovery);window.dispatchEvent(new Event('notebook-local'));window.dispatchEvent(new Event('coach-local'));return {drafts,recovery:recovery.length};}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if(document.querySelector('#workspace-backup')){const dialog=document.createElement('dialog');dialog.innerHTML='<h2>全部模块备份</h2><p>包含已保存的记录、历史版本、本机草稿与图片。不包含密码、令牌或授权。</p><button id="backup-download">下载全部备份</button><label class="button">恢复全部备份<input id="backup-import" type="file" accept=".json,application/json" hidden></label><button id="backup-close">关闭</button><p id="backup-message" role="status"></p><div id="recovered-drafts"></div>';document.body.append(dialog);const status=dialog.querySelector('#backup-message');let busy=false;async function run(fn){if(busy)return;busy=true;status.textContent='正在处理，请勿关闭页面…';try{await fn();await render();}catch(e){status.textContent=e.message+'。本机原有记录保留。';}finally{busy=false;}}async function render(){const list=dialog.querySelector('#recovered-drafts');list.replaceChildren();for(const r of await modules[0].store.get('workspace-restored-drafts')||[]){const row=document.createElement('p'),b=document.createElement('button');row.textContent=(modules.find(m=>m.id===r.module)?.name||'')+' · 冲突草稿 '+r.key;b.textContent='下载这份草稿（含图片）';b.onclick=()=>void run(async()=>{const m=modules.find(m=>m.id===r.module),assets={};for(const id of refs(r.value))assets[id]=await m.store.get(id,'assets');download({draft:r,assets},'找回草稿.json');status.textContent='冲突草稿已导出；当前草稿没有被覆盖。';});const open=document.createElement('button');open.textContent='恢复到编辑器';open.onclick=()=>void run(async()=>{await window.workspaceFlush?.();const m=modules.find(m=>m.id===r.module),all=await modules[0].store.get('workspace-restored-drafts')||[],old=await m.store.get(r.key);const remaining=all.filter(v=>JSON.stringify(v)!==JSON.stringify(r));if(old!=null&&JSON.stringify(old)!==JSON.stringify(r.value))remaining.push({module:r.module,key:r.key,value:old,at:new Date().toISOString()});await modules[0].store.set('workspace-restored-drafts',remaining);await m.store.set(r.key,r.value);status.textContent='已恢复这份草稿，原草稿已另外保留。刷新页面后查看；课题草稿请打开对应课题。';});row.append(b,open);list.append(row);}}document.querySelector('#workspace-backup').onclick=()=>{dialog.showModal();void render();};dialog.querySelector('#backup-close').onclick=()=>dialog.close();dialog.querySelector('#backup-download').onclick=()=>void run(async()=>{const data=await exportWorkspace();download(data,'纸间全部备份-'+new Date().toISOString().slice(0,10)+'.json');status.textContent='全部模块、草稿和图片已导出。请妥善保管备份文件。';});dialog.querySelector('#backup-import').onchange=e=>void run(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>200000000)throw Error('备份超过 200 MB，请分模块恢复');await window.workspaceFlush?.();const result=await importWorkspace(JSON.parse(await f.text()));status.textContent='恢复完成，历史已合并。草稿 '+result.drafts+' 份；冲突草稿 '+result.recovery+' 份已另外保留。刷新页面查看恢复的草稿（需重新解锁同步）。';e.target.value='';});}
