import {get,set,snapshot,put,storeImage,exportBackup,importBackup} from './store.js';
import {rows,heads,conflicts} from './model.js';
import {connect,remember,unlock,synchronize,lock,syncMessage} from './sync.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const blank=()=>({date:today(),text:'',result:'',plan:'',ref:'',state:'ongoing',images:[]});
let journal,selected='',draft=blank(),pending=Promise.resolve(),busy=false,dirty=false,vault=false,filter='';
const states={ongoing:'进行中',blocked:'遇到问题',done:'本步完成'};
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6000);}
async function run(fn){try{await fn();}catch(e){toast(e.message);}}
const project=()=>rows(journal,'paper').find(p=>p.id===selected);
const version=(table,id)=>heads(journal,table,id).map(e=>e.id).sort().join();
function capture(){if(!$('#entry-form'))return;for(const key of ['date','text','result','plan','ref','state'])draft[key]=$('#field-'+key).value;}
function persist(){if(!selected)return pending;capture();const id=selected,value=structuredClone(draft);dirty=true;$('#save-state').textContent='正在保存草稿…';pending=pending.catch(()=>{}).then(()=>set('draft-'+id,value)).then(()=>{dirty=false;$('#save-state').textContent='草稿已保存到本机';});return pending;}
function sidebar(){const show=$('#show-archived').checked,q=$('#project-search').value.toLowerCase();$('#paper-list').innerHTML=rows(journal,'paper').filter(p=>(show||!p.archived)&&p.title.toLowerCase().includes(q)).map(p=>`<button class="paper-item ${p.id===selected?'selected':''}" data-project="${esc(p.id)}"><h3>${esc(p.title)}</h3><small>${p.archived?'已归档 · ':''}${rows(journal,'note').filter(n=>n.paperId===p.id&&!n.archived).length} 条进展</small></button>`).join('')||'<p class="muted">还没有课题，点击上方新建。</p>';}
async function choose(id){if(busy)return;busy=true;try{await persist();selected=id;await set('selected-project',id);draft=await get('draft-'+id)||blank();filter='';render();}finally{busy=false;}}
function render(){sidebar();const p=project();if(!p){$('#main').innerHTML='<section class="welcome"><span class="eyebrow">YOUR RESEARCH JOURNEY</span><h2>把每一步，<br>留在自己的课题里。</h2><p>记录做了什么、得到了什么，<br>以及下一步准备怎么做。</p><button id="first-project" class="primary">＋ 新建第一个课题</button></section>';return;}
 $('#main').innerHTML=`<div class="paper-head-top"><div><span class="eyebrow">RESEARCH PROGRESS</span><h2>${esc(p.title)}</h2><p class="meta">${esc(p.source||'按时间串起计算进展、结果与下一步计划。')}</p></div><div class="row"><button id="rename-project">编辑课题</button><button id="archive-project">${p.archived?'恢复课题':'归档课题'}</button></div></div>${p.archived?'<p class="archived-banner">课题已归档。恢复后可以继续记录。</p>':`<form id="entry-form" class="composer"><h3>${draft.editId?'编辑进展':'记录这一步'}</h3><div class="form-row"><label>记录日期<input id="field-date" type="date" required value="${esc(draft.date)}"></label><label>本步状态<select id="field-state">${Object.entries(states).map(([k,v])=>`<option value="${k}" ${draft.state===k?'selected':''}>${v}</option>`).join('')}</select></label></div><label>进展 · 做了什么<textarea id="field-text" maxlength="100000" placeholder="例如：完成第一轮结构优化，检查了收敛情况。">${esc(draft.text)}</textarea></label><label>结果与判断<textarea id="field-result" maxlength="100000" placeholder="记录得到的结果、你的解释和仍不确定的地方。">${esc(draft.result)}</textarea></label><label>下一步计划<textarea id="field-plan" maxlength="100000" placeholder="下一步准备计算什么、核对什么，或解决哪个问题？">${esc(draft.plan)}</textarea></label><details ${draft.ref?'open':''}><summary>计算任务、参数或文件位置（可选）</summary><textarea id="field-ref" maxlength="2000" placeholder="任务编号、软件与参数版本、文件路径或链接">${esc(draft.ref)}</textarea></details><div id="draft-images" class="images"></div><div class="composer-foot"><label class="button">＋ 结果截图<input id="image-upload" type="file" accept="image/*" multiple hidden></label><div class="row">${draft.editId?'<button type="button" id="cancel-edit">取消编辑</button>':''}<button id="save-entry" class="primary">${draft.editId?'保存修改':'保存进展'}</button></div></div><p class="draft-info">草稿按课题分别保存在本机。保存后参与备份和同步；支持粘贴截图。</p></form>`}<div class="note-tabs"><h3>进展时间线</h3><label><input id="show-record-archive" type="checkbox"> 包含归档记录</label></div><input id="record-search" type="search" placeholder="搜索本课题的进展、结果、计划" aria-label="搜索进展"><div id="notes"></div>`;
 if($('#entry-form'))$('#entry-form').onsubmit=e=>{e.preventDefault();void run(save);};draftImages();list();}
async function loadImages(box){for(const img of box?.querySelectorAll('[data-image]')||[]){const data=await get(img.dataset.image,'assets');if(data)img.src=data;else img.alt='截图尚未下载，请同步';}}
function draftImages(){if(!$('#draft-images'))return;$('#draft-images').innerHTML=draft.images.map((id,i)=>`<div class="image-wrap"><img data-image="${esc(id)}" alt="结果截图"><button type="button" data-remove="${i}">×</button></div>`).join('');void loadImages($('#draft-images'));}
function list(){if(!$('#notes'))return;const show=$('#show-record-archive').checked;const notes=rows(journal,'note').filter(n=>n.paperId===selected&&(show||!n.archived)).filter(n=>[n.text,n.result,n.plan,n.ref].join(' ').toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt-a.updatedAt);$('#notes').innerHTML=notes.map(n=>`<article class="note-card"><div class="note-top"><time>${esc(n.date)}</time><span class="badge">${n.archived?'已归档 · ':''}${states[n.state]}</span></div>${[['进展',n.text],['结果与判断',n.result],['下一步计划',n.plan],['任务与文件',n.ref]].filter(([,v])=>v).map(([label,v])=>`<h4>${label}</h4><p class="note-text">${esc(v)}</p>`).join('')}<div class="images">${n.images.map(id=>`<img data-image="${esc(id)}" alt="结果截图，点击放大" tabindex="0" role="button">`).join('')}</div><div class="note-actions"><button data-edit="${esc(n.id)}">编辑</button><button data-archive="${esc(n.id)}">${n.archived?'恢复':'归档'}</button></div></article>`).join('')||'<p class="empty">暂无记录，从上方记下第一步。</p>';void loadImages($('#notes'));}
async function save(){if(busy)return;capture();if(!draft.text.trim()&&!draft.result.trim()&&!draft.plan.trim()&&!draft.images.length)throw Error('请先记录一点内容或添加截图');busy=true;$('#save-entry').disabled=true;try{await persist();journal=await snapshot();const old=rows(journal,'note').find(n=>n.id===draft.editId);await put('note',{...old,id:draft.editId||crypto.randomUUID(),paperId:selected,kind:'note',locator:'',archived:old?.archived||false,date:draft.date,text:draft.text,result:draft.result,plan:draft.plan,ref:draft.ref,state:draft.state,images:[...draft.images]},false,draft.editId?draft.baseHeads:undefined);draft=blank();await set('draft-'+selected,draft);journal=await snapshot();render();toast('进展已保存');}finally{busy=false;if($('#save-entry'))$('#save-entry').disabled=false;}}
async function editProject(existing){if(busy)return;await persist();let d=$('#project-dialog');if(!d){d=document.createElement('dialog');d.id='project-dialog';d.innerHTML='<form id="project-form"><h2>课题信息</h2><label>课题名称<input name="title" maxlength="1000" required></label><label>目标或简介（可选）<textarea name="description" maxlength="2000"></textarea></label><div class="dialog-actions"><button type="button" data-close="project-dialog">取消</button><button class="primary">保存课题</button></div></form>';document.body.append(d);}const form=$('#project-form');form.elements.title.value=existing?.title||'';form.elements.description.value=existing?.source||'';const expected=existing?version('paper',existing.id):undefined;form.onsubmit=e=>{e.preventDefault();void run(async()=>{const title=form.elements.title.value.trim();if(!title)throw Error('请填写课题名称');const id=existing?.id||crypto.randomUUID();await put('paper',{id,title,source:form.elements.description.value,authors:'',year:'',tags:'',status:'reading',archived:existing?.archived||false},false,expected);d.close();journal=await snapshot();await choose(id);});};d.showModal();}
async function addImages(files){if(busy||!selected||project()?.archived)return;if(draft.images.length+files.length>20)throw Error('每条记录最多 20 张截图');busy=true;try{for(const f of files){const id=await storeImage(f);if(!draft.images.includes(id))draft.images.push(id);await persist();}draftImages();}finally{busy=false;}}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function dataDialog(){vault=!!await get('vault');$('#sync-config').hidden=vault;$('#sync-connect').textContent=vault?'解锁自动同步':'连接并加密保存授权';$('#sync-state').textContent=syncMessage;$('#conflicts').innerHTML=conflicts(await snapshot()).map(c=>'<h3>并行版本 · 请选择保留版本</h3>'+c.versions.map(e=>`<pre>${esc(JSON.stringify(e.value,null,2))}</pre><button data-resolve="${esc(e.id)}">使用此版本</button>`).join('')).join('');$('#data-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-image]');if(!b)return;void run(async()=>{if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.image){const data=await get(b.dataset.image,'assets');if(data){$('#full-image').src=data;$('#image-dialog').showModal();}return;}if(b.dataset.project){await choose(b.dataset.project);return;}if(b.dataset.resolve){const d=await snapshot(),v=d.events.find(x=>x.id===b.dataset.resolve);await put(v.table,v.value,true);journal=await snapshot();$('#data-dialog').close();await dataDialog();sidebar();list();return;}if(busy)return;if(b.dataset.remove!==undefined){draft.images.splice(+b.dataset.remove,1);await persist();draftImages();return;}if(b.dataset.edit){if(draft.text||draft.result||draft.plan||draft.images.length){if(!confirm('当前草稿将被替换，继续编辑这条记录？'))return;}await pending;const n=rows(journal,'note').find(n=>n.id===b.dataset.edit);if(project().archived)throw Error('请先恢复课题');draft={...n,editId:n.id,baseHeads:version('note',n.id)};await set('draft-'+selected,draft);render();$('#entry-form').scrollIntoView();return;}if(b.dataset.archive){const n=rows(journal,'note').find(n=>n.id===b.dataset.archive);await put('note',{...n,archived:!n.archived},false,version('note',n.id));journal=await snapshot();sidebar();list();return;}switch(b.id){case 'first-project':case 'new-project':await editProject();break;case 'rename-project':await editProject(project());break;case 'archive-project':await persist();await put('paper',{...project(),archived:!project().archived},false,version('paper',selected));journal=await snapshot();render();break;case 'cancel-edit':await pending;draft=blank();await set('draft-'+selected,draft);render();break;case 'data-open':await dataDialog();break;case 'export-all':await pending;download(await exportBackup(),'research-progress-'+today()+'.json');$('#backup-state').textContent='完整备份已下载（未提交草稿不包含在内）';break;case 'sync-now':await synchronize();break;case 'sync-lock':lock();break;case 'sync-reset':lock();await set('vault',null);$('#data-dialog').close();await dataDialog();break;}});});
document.addEventListener('input',e=>{if(e.target.closest('#entry-form'))void run(persist);if(e.target.id==='project-search')sidebar();if(e.target.id==='record-search'){filter=e.target.value;list();}});
document.addEventListener('change',e=>{if(e.target.id==='show-archived')sidebar();if(e.target.id==='show-record-archive')list();if(e.target.id==='image-upload'){const files=[...e.target.files];e.target.value='';void run(()=>addImages(files));}if(e.target.id==='import-all'){const f=e.target.files[0];e.target.value='';if(f)void run(async()=>{if(f.size>150*1024*1024)throw Error('备份不能超过 150 MB');await importBackup(JSON.parse(await f.text()));journal=await snapshot();if(!selected)await choose(rows(journal,'paper')[0]?.id||'');else{sidebar();list();}$('#backup-state').textContent='备份已合并，保留历史版本';});}});
document.addEventListener('paste',e=>{if(!e.target.closest('#entry-form'))return;const files=[...(e.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();void run(()=>addImages(files));}});
document.addEventListener('keydown',e=>{if(e.target.matches('img[data-image]')&&e.key==='Enter')e.target.click();});
$('#sync-form').onsubmit=e=>{e.preventDefault();void run(async()=>{const f=e.target,b=$('#sync-connect');b.disabled=true;try{if(vault)await unlock(f.elements.password.value);else{const c={owner:f.elements.owner.value.trim(),repo:f.elements.repo.value.trim()};await connect(c,f.elements.token.value);await remember(c,f.elements.token.value,f.elements.password.value);}f.elements.token.value='';f.elements.password.value='';vault=true;$('#sync-config').hidden=true;$('#sync-connect').textContent='解锁自动同步';}finally{b.disabled=false;}});};
window.addEventListener('notebook-sync',()=>$('#sync-state').textContent=syncMessage);window.addEventListener('notebook-remote',()=>void run(async()=>{journal=await snapshot();sidebar();list();}));window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
async function init(){journal=await snapshot();selected=await get('selected-project')||rows(journal,'paper').find(p=>!p.archived)?.id||'';draft=await get('draft-'+selected)||blank();render();}
void run(init);
