import {empty,merge,append,validate,heads} from './model.js';
let connection;
export function db(){return connection??=new Promise((resolve,reject)=>{const r=indexedDB.open('research-progress-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('data');r.result.createObjectStore('assets');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function get(key,store='data'){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function set(key,value,store='data'){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
export const snapshot=async()=>await get('journal')??empty();
export async function put(table,value,resolve=false,expectedHeads){return navigator.locks.request('research-progress-write',async()=>{const d=await snapshot();if(expectedHeads!==undefined&&heads(d,table,value.id).map(e=>e.id).sort().join()!==expectedHeads)throw Error('记录已在其他页面或电脑更新，草稿仍保留，请先核对最新版本');append(d,table,value,resolve);await set('journal',d);window.dispatchEvent(new Event('notebook-local'));});}
export async function receive(remote){return navigator.locks.request('research-progress-write',async()=>{const d=merge(await snapshot(),validate(remote));await set('journal',d);window.dispatchEvent(new Event('notebook-remote'));});}
export async function imageId(data){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(data));return 'img-'+[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function storeImage(file){if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('请选择 PNG、JPEG、WebP 或 GIF 图片');if(file.size>20*1024*1024)throw Error('单张原图请小于 20 MB');const bitmap=await createImageBitmap(file);try{const ratio=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/webp',.9);if(data.length>800000)data=canvas.toDataURL('image/webp',.7);if(data.length>800000)throw Error('这张截图仍然过大，请裁剪后再添加（每张压缩后最多约 600 KB）');const id=await imageId(data);await set(id,data,'assets');return id;}finally{bitmap.close();}}
export function assetIds(d){return [...new Set(d.events.filter(e=>e.table==='note').flatMap(e=>e.value.images))];}
export async function exportBackup(){const journal=await snapshot(),assets={};for(const id of assetIds(journal)){const data=await get(id,'assets');if(!data)throw Error('有截图尚未下载，请先完成同步再备份');assets[id]=data;}return {format:'research-progress-backup',schemaVersion:1,journal,assets};}
export async function importBackup(input){if(input?.format!=='research-progress-backup'||input.schemaVersion!==1||!input.assets)throw Error('请选择本应用导出的完整备份');const journal=validate(input.journal);for(const id of assetIds(journal)){const data=input.assets[id];if(typeof data!=='string'||data.length>800000||!/^data:image\/(webp|png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(data)||await imageId(data)!==id)throw Error('备份截图缺失或校验失败');}
 return navigator.locks.request('research-progress-write',async()=>{const combined=merge(await snapshot(),journal),d=await db();await new Promise((resolve,reject)=>{const t=d.transaction(['data','assets'],'readwrite');t.objectStore('data').put(combined,'journal');for(const id of assetIds(journal))t.objectStore('assets').put(input.assets[id],id);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});window.dispatchEvent(new Event('notebook-local'));});}
